# Generated by Django 5.1.3 on 2024-12-02 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_auctionlistings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionListings',
            new_name='AuctionListing',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
