# Generated by Django 5.1.3 on 2024-12-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_auction_bid_bid_date_bid_user_comment_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
