# Generated by Django 5.1.3 on 2024-12-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='price1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
