# Generated by Django 5.1.3 on 2024-12-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_price1_alter_auctionlisting_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='price1',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
