# Generated by Django 5.1.3 on 2024-12-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('auction', 'user')},
        ),
    ]
