# Generated by Django 5.1.4 on 2024-12-19 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='description',
            field=models.TextField(max_length=450),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='img_url',
            field=models.URLField(blank=True, default='https://placeholder.pics/svg/300/FBFFBC-C7FF63/000000-9BA6FF/example%20image'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
        ),
    ]
