# Generated by Django 5.1.4 on 2024-12-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auctionlisting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='img_url',
            field=models.URLField(default='https://placeholder.pics/svg/300/FBFFBC-C7FF63/000000-9BA6FF/example%20image'),
        ),
    ]
