# Generated by Django 5.1.4 on 2024-12-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_category_description_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='img_url',
            field=models.URLField(default='http://placeholder.pics/svg/600x400/DEDEDE/555555/example%20image'),
        ),
    ]
